"""Drop unused columns

Revision ID: c07454788650
Revises: 747005db1d96
Create Date: 2023-09-25 00:06:03.686357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c07454788650'
down_revision = '747005db1d96'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'court')
    op.drop_column('companies', 'NIP')
    op.drop_column('companies', 'KRS')
    op.drop_column('companies', 'REGON')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('REGON', sa.VARCHAR(), nullable=True))
    op.add_column('companies', sa.Column('KRS', sa.VARCHAR(), nullable=True))
    op.add_column('companies', sa.Column('NIP', sa.VARCHAR(), nullable=True))
    op.add_column('companies', sa.Column('court', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
