"""Remove checked table

Revision ID: d113ef56aa61
Revises: ac6cf7c989b4
Create Date: 2023-02-13 16:55:14.797625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d113ef56aa61"
down_revision = "ac6cf7c989b4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("checked")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "checked",
        sa.Column("company_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name="fk_checked_company_id_companies",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name="fk_checked_user_id_users",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
    )
    # ### end Alembic commands ###
