"""init

Revision ID: 01834b4ffe22
Revises: 
Create Date: 2023-06-14 06:27:52.744363

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "01834b4ffe22"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("fullname", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column("password", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("name", name=op.f("uq_users_name")),
    )
    op.create_table(
        "companies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("street", sa.String(), nullable=True),
        sa.Column("postcode", sa.String(), nullable=True),
        sa.Column("city", sa.String(), nullable=True),
        sa.Column("subdivision", sa.String(), nullable=True),
        sa.Column("country", sa.String(), nullable=True),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column("link", sa.String(), nullable=True),
        sa.Column("NIP", sa.String(), nullable=True),
        sa.Column("REGON", sa.String(), nullable=True),
        sa.Column("KRS", sa.String(), nullable=True),
        sa.Column("court", sa.String(), nullable=True),
        sa.Column("color", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("creator_id", sa.Integer(), nullable=True),
        sa.Column("editor_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["creator_id"],
            ["users.id"],
            name=op.f("fk_companies_creator_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["editor_id"],
            ["users.id"],
            name=op.f("fk_companies_editor_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_companies")),
    )
    op.create_index(
        op.f("ix_companies_creator_id"), "companies", ["creator_id"], unique=False
    )
    op.create_index(
        op.f("ix_companies_editor_id"), "companies", ["editor_id"], unique=False
    )
    op.create_table(
        "projects",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("street", sa.String(), nullable=True),
        sa.Column("postcode", sa.String(), nullable=True),
        sa.Column("city", sa.String(), nullable=True),
        sa.Column("subdivision", sa.String(), nullable=True),
        sa.Column("country", sa.String(), nullable=True),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column("link", sa.String(), nullable=True),
        sa.Column("color", sa.String(), nullable=True),
        sa.Column("deadline", sa.DateTime(), nullable=True),
        sa.Column("stage", sa.String(), nullable=True),
        sa.Column("delivery_method", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("creator_id", sa.Integer(), nullable=True),
        sa.Column("editor_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["creator_id"],
            ["users.id"],
            name=op.f("fk_projects_creator_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["editor_id"],
            ["users.id"],
            name=op.f("fk_projects_editor_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_projects")),
    )
    op.create_index(
        op.f("ix_projects_creator_id"), "projects", ["creator_id"], unique=False
    )
    op.create_index(
        op.f("ix_projects_editor_id"), "projects", ["editor_id"], unique=False
    )
    op.create_table(
        "tags",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("creator_id", sa.Integer(), nullable=True),
        sa.Column("editor_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["creator_id"],
            ["users.id"],
            name=op.f("fk_tags_creator_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["editor_id"],
            ["users.id"],
            name=op.f("fk_tags_editor_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tags")),
    )
    op.create_index(op.f("ix_tags_creator_id"), "tags", ["creator_id"], unique=False)
    op.create_index(op.f("ix_tags_editor_id"), "tags", ["editor_id"], unique=False)
    op.create_table(
        "themes",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("theme", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_themes_user_id_users"),
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_themes")),
    )
    op.create_index(op.f("ix_themes_user_id"), "themes", ["user_id"], unique=False)
    op.create_table(
        "activity",
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("stage", sa.String(), nullable=True),
        sa.Column("role", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_activity_company_id_companies"),
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_activity_project_id_projects"),
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("company_id", "project_id", name=op.f("pk_activity")),
    )
    op.create_index(
        op.f("ix_activity_company_id"), "activity", ["company_id"], unique=False
    )
    op.create_index(
        op.f("ix_activity_project_id"), "activity", ["project_id"], unique=False
    )
    op.create_table(
        "comments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("comment", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("creator_id", sa.Integer(), nullable=True),
        sa.Column("editor_id", sa.Integer(), nullable=True),
        sa.Column("company_id", sa.Integer(), nullable=True),
        sa.Column("project_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_comments_company_id_companies"),
        ),
        sa.ForeignKeyConstraint(
            ["creator_id"],
            ["users.id"],
            name=op.f("fk_comments_creator_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["editor_id"],
            ["users.id"],
            name=op.f("fk_comments_editor_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_comments_project_id_projects"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_comments")),
    )
    op.create_index(
        op.f("ix_comments_company_id"), "comments", ["company_id"], unique=False
    )
    op.create_index(
        op.f("ix_comments_creator_id"), "comments", ["creator_id"], unique=False
    )
    op.create_index(
        op.f("ix_comments_editor_id"), "comments", ["editor_id"], unique=False
    )
    op.create_index(
        op.f("ix_comments_project_id"), "comments", ["project_id"], unique=False
    )
    op.create_table(
        "companies_stars",
        sa.Column("company_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_companies_stars_company_id_companies"),
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_companies_stars_user_id_users"),
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
    )
    op.create_index(
        op.f("ix_companies_stars_company_id"),
        "companies_stars",
        ["company_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_companies_stars_user_id"), "companies_stars", ["user_id"], unique=False
    )
    op.create_table(
        "companies_tags",
        sa.Column("company_id", sa.Integer(), nullable=True),
        sa.Column("tag_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_companies_tags_company_id_companies"),
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["tags.id"],
            name=op.f("fk_companies_tags_tag_id_tags"),
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
    )
    op.create_index(
        op.f("ix_companies_tags_company_id"),
        "companies_tags",
        ["company_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_companies_tags_tag_id"), "companies_tags", ["tag_id"], unique=False
    )
    op.create_table(
        "contacts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("role", sa.String(), nullable=True),
        sa.Column("phone", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("creator_id", sa.Integer(), nullable=True),
        sa.Column("editor_id", sa.Integer(), nullable=True),
        sa.Column("company_id", sa.Integer(), nullable=True),
        sa.Column("project_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_contacts_company_id_companies"),
        ),
        sa.ForeignKeyConstraint(
            ["creator_id"],
            ["users.id"],
            name=op.f("fk_contacts_creator_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["editor_id"],
            ["users.id"],
            name=op.f("fk_contacts_editor_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_contacts_project_id_projects"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_contacts")),
    )
    op.create_index(
        op.f("ix_contacts_company_id"), "contacts", ["company_id"], unique=False
    )
    op.create_index(
        op.f("ix_contacts_creator_id"), "contacts", ["creator_id"], unique=False
    )
    op.create_index(
        op.f("ix_contacts_editor_id"), "contacts", ["editor_id"], unique=False
    )
    op.create_index(
        op.f("ix_contacts_project_id"), "contacts", ["project_id"], unique=False
    )
    op.create_table(
        "projects_stars",
        sa.Column("project_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_projects_stars_project_id_projects"),
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_projects_stars_user_id_users"),
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
    )
    op.create_index(
        op.f("ix_projects_stars_project_id"),
        "projects_stars",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_projects_stars_user_id"), "projects_stars", ["user_id"], unique=False
    )
    op.create_table(
        "projects_tags",
        sa.Column("project_id", sa.Integer(), nullable=True),
        sa.Column("tag_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_projects_tags_project_id_projects"),
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["tags.id"],
            name=op.f("fk_projects_tags_tag_id_tags"),
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
    )
    op.create_index(
        op.f("ix_projects_tags_project_id"),
        "projects_tags",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_projects_tags_tag_id"), "projects_tags", ["tag_id"], unique=False
    )
    op.create_table(
        "selected_companies",
        sa.Column("company_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_selected_companies_company_id_companies"),
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_selected_companies_user_id_users"),
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
    )
    op.create_index(
        op.f("ix_selected_companies_company_id"),
        "selected_companies",
        ["company_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_selected_companies_user_id"),
        "selected_companies",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "selected_projects",
        sa.Column("project_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_selected_projects_project_id_projects"),
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_selected_projects_user_id_users"),
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
    )
    op.create_index(
        op.f("ix_selected_projects_project_id"),
        "selected_projects",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_selected_projects_user_id"),
        "selected_projects",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "selected_tags",
        sa.Column("tag_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["tags.id"],
            name=op.f("fk_selected_tags_tag_id_tags"),
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_selected_tags_user_id_users"),
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
    )
    op.create_index(
        op.f("ix_selected_tags_tag_id"), "selected_tags", ["tag_id"], unique=False
    )
    op.create_index(
        op.f("ix_selected_tags_user_id"), "selected_tags", ["user_id"], unique=False
    )
    op.create_table(
        "selected_contacts",
        sa.Column("contact_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["contact_id"],
            ["contacts.id"],
            name=op.f("fk_selected_contacts_contact_id_contacts"),
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_selected_contacts_user_id_users"),
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
    )
    op.create_index(
        op.f("ix_selected_contacts_contact_id"),
        "selected_contacts",
        ["contact_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_selected_contacts_user_id"),
        "selected_contacts",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_selected_contacts_user_id"), table_name="selected_contacts")
    op.drop_index(
        op.f("ix_selected_contacts_contact_id"), table_name="selected_contacts"
    )
    op.drop_table("selected_contacts")
    op.drop_index(op.f("ix_selected_tags_user_id"), table_name="selected_tags")
    op.drop_index(op.f("ix_selected_tags_tag_id"), table_name="selected_tags")
    op.drop_table("selected_tags")
    op.drop_index(op.f("ix_selected_projects_user_id"), table_name="selected_projects")
    op.drop_index(
        op.f("ix_selected_projects_project_id"), table_name="selected_projects"
    )
    op.drop_table("selected_projects")
    op.drop_index(
        op.f("ix_selected_companies_user_id"), table_name="selected_companies"
    )
    op.drop_index(
        op.f("ix_selected_companies_company_id"), table_name="selected_companies"
    )
    op.drop_table("selected_companies")
    op.drop_index(op.f("ix_projects_tags_tag_id"), table_name="projects_tags")
    op.drop_index(op.f("ix_projects_tags_project_id"), table_name="projects_tags")
    op.drop_table("projects_tags")
    op.drop_index(op.f("ix_projects_stars_user_id"), table_name="projects_stars")
    op.drop_index(op.f("ix_projects_stars_project_id"), table_name="projects_stars")
    op.drop_table("projects_stars")
    op.drop_index(op.f("ix_contacts_project_id"), table_name="contacts")
    op.drop_index(op.f("ix_contacts_editor_id"), table_name="contacts")
    op.drop_index(op.f("ix_contacts_creator_id"), table_name="contacts")
    op.drop_index(op.f("ix_contacts_company_id"), table_name="contacts")
    op.drop_table("contacts")
    op.drop_index(op.f("ix_companies_tags_tag_id"), table_name="companies_tags")
    op.drop_index(op.f("ix_companies_tags_company_id"), table_name="companies_tags")
    op.drop_table("companies_tags")
    op.drop_index(op.f("ix_companies_stars_user_id"), table_name="companies_stars")
    op.drop_index(op.f("ix_companies_stars_company_id"), table_name="companies_stars")
    op.drop_table("companies_stars")
    op.drop_index(op.f("ix_comments_project_id"), table_name="comments")
    op.drop_index(op.f("ix_comments_editor_id"), table_name="comments")
    op.drop_index(op.f("ix_comments_creator_id"), table_name="comments")
    op.drop_index(op.f("ix_comments_company_id"), table_name="comments")
    op.drop_table("comments")
    op.drop_index(op.f("ix_activity_project_id"), table_name="activity")
    op.drop_index(op.f("ix_activity_company_id"), table_name="activity")
    op.drop_table("activity")
    op.drop_index(op.f("ix_themes_user_id"), table_name="themes")
    op.drop_table("themes")
    op.drop_index(op.f("ix_tags_editor_id"), table_name="tags")
    op.drop_index(op.f("ix_tags_creator_id"), table_name="tags")
    op.drop_table("tags")
    op.drop_index(op.f("ix_projects_editor_id"), table_name="projects")
    op.drop_index(op.f("ix_projects_creator_id"), table_name="projects")
    op.drop_table("projects")
    op.drop_index(op.f("ix_companies_editor_id"), table_name="companies")
    op.drop_index(op.f("ix_companies_creator_id"), table_name="companies")
    op.drop_table("companies")
    op.drop_table("users")
    # ### end Alembic commands ###
