"""Identification numbers

Revision ID: 965c3826a7aa
Revises: 984e5cba2065
Create Date: 2023-09-24 22:30:50.538728

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "965c3826a7aa"
down_revision = "984e5cba2065"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "identification_numbers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("NIP", sa.String(), nullable=True),
        sa.Column("REGON", sa.String(), nullable=True),
        sa.Column("KRS", sa.String(), nullable=True),
        sa.Column("sad", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("creator_id", sa.Integer(), nullable=True),
        sa.Column("editor_id", sa.Integer(), nullable=True),
        sa.Column("company_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_identification_numbers_company_id_companies"),
        ),
        sa.ForeignKeyConstraint(
            ["creator_id"],
            ["users.id"],
            name=op.f("fk_identification_numbers_creator_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["editor_id"],
            ["users.id"],
            name=op.f("fk_identification_numbers_editor_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_identification_numbers")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("identification_numbers")
    # ### end Alembic commands ###
