"""Remove themes table

Revision ID: b522888918c5
Revises: 97209f739ca8
Create Date: 2025-07-27 17:00:59.691115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b522888918c5'
down_revision = '97209f739ca8'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('themes')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('themes',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('theme', sa.VARCHAR(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_themes_user_id_users'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_themes'))
    )
    # ### end Alembic commands ###
