"""Moved identification numbers to company

Revision ID: fa855bc5d525
Revises: 39a2989cf4d7
Create Date: 2025-06-20 20:43:16.521528

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.orm.session import Session

from marker.models import IdentificationNumber

# revision identifiers, used by Alembic.
revision = "fa855bc5d525"
down_revision = "39a2989cf4d7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("companies", sa.Column("NIP", sa.String(), nullable=True))
    op.add_column("companies", sa.Column("REGON", sa.String(), nullable=True))
    op.add_column("companies", sa.Column("KRS", sa.String(), nullable=True))
    op.add_column("companies", sa.Column("court", sa.String(), nullable=True))

    session = Session(bind=op.get_bind())
    identification_numbers = session.execute(sa.select(IdentificationNumber)).scalars()
    for identification_number in identification_numbers:
        company = identification_number.company
        if company:
            company.NIP = identification_number.NIP
            company.REGON = identification_number.REGON
            company.KRS = identification_number.KRS
            company.court = identification_number.court
        else:
            continue
    session.commit()

    op.drop_table("identification_numbers")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("companies", "court")
    op.drop_column("companies", "KRS")
    op.drop_column("companies", "REGON")
    op.drop_column("companies", "NIP")
    op.create_table(
        "identification_numbers",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("NIP", sa.VARCHAR(), nullable=True),
        sa.Column("REGON", sa.VARCHAR(), nullable=True),
        sa.Column("KRS", sa.VARCHAR(), nullable=True),
        sa.Column("court", sa.VARCHAR(), nullable=True),
        sa.Column("created_at", sa.DATETIME(), nullable=False),
        sa.Column("updated_at", sa.DATETIME(), nullable=True),
        sa.Column("creator_id", sa.INTEGER(), nullable=True),
        sa.Column("editor_id", sa.INTEGER(), nullable=True),
        sa.Column("company_id", sa.INTEGER(), nullable=True),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_identification_numbers_company_id_companies"),
        ),
        sa.ForeignKeyConstraint(
            ["creator_id"],
            ["users.id"],
            name=op.f("fk_identification_numbers_creator_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["editor_id"],
            ["users.id"],
            name=op.f("fk_identification_numbers_editor_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_identification_numbers")),
    )
    # ### end Alembic commands ###
