"""Removes court column from companies

Revision ID: ef6388976d02
Revises: 6f7a9c1e2b3d
Create Date: 2026-03-28 13:28:30.379209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef6388976d02'
down_revision = '6f7a9c1e2b3d'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'court')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('court', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
