"""Add usable_area, cubic_volume, currency, value_net, value_gross to projects

Revision ID: 6ae8eb2273ab
Revises: ef6388976d02
Create Date: 2026-04-11 19:18:15.557803

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "6ae8eb2273ab"
down_revision = "ef6388976d02"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("projects", sa.Column("usable_area", sa.Numeric(), nullable=True))
    op.add_column("projects", sa.Column("cubic_volume", sa.Numeric(), nullable=True))
    op.add_column("projects", sa.Column("currency", sa.String(), nullable=True))
    op.add_column("projects", sa.Column("value_net", sa.Numeric(), nullable=True))
    op.add_column("projects", sa.Column("value_gross", sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "value_gross")
    op.drop_column("projects", "value_net")
    op.drop_column("projects", "currency")
    op.drop_column("projects", "cubic_volume")
    op.drop_column("projects", "usable_area")
    # ### end Alembic commands ###
