"""Added color to contact

Revision ID: 163919059dcc
Revises: b522888918c5
Create Date: 2026-02-22 17:18:03.740691

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "163919059dcc"
down_revision = "b522888918c5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("contacts", sa.Column("color", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("contacts", "color")
    # ### end Alembic commands ###
