VOIVODESHIPS = (
    ('', ''),
    ('DS', 'dolnośląskie'),
    ('KP', 'kujawsko-pomorskie'),
    ('LU', 'lubelskie'),
    ('LB', 'lubuskie'),
    ('LD', 'łódzkie'),
    ('MP', 'małopolskie'),
    ('MA', 'mazowieckie'),
    ('OP', 'opolskie'),
    ('PK', 'podkarpackie'),
    ('PD', 'podlaskie'),
    ('PM', 'pomorskie'),
    ('SL', 'śląskie'),
    ('SW', 'świętokrzyskie'),
    ('WM', 'warmińsko-mazurskie'),
    ('WP', 'wielkopolskie'),
    ('ZP', 'zachodniopomorskie'),
)
