from .login import LoginForm  # flake8: noqa
from .account import Account  # flake8: noqa
from .account import ChangePassword  # flake8: noqa
from .report import ReportForm  # flake8: noqa
from .tag import TagForm  # flake8: noqa
from .user import UserForm  # flake8: noqa
from .comment import CommentForm  # flake8: noqa
from .company import CompanyForm  # flake8: noqa
from .project import ProjectForm  # flake8: noqa
from .person import PersonForm  # flake8: noqa